spring:
  application:
    name: nexus-api
  
  datasource:
    # H2 In-Memory Database (for local testing)
    url: jdbc:h2:mem:nexusdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
  
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
